export const cottageInputs = [
  {
    id:1,
    name:"cottageName",
    type:"text",
    placeholder:"Nova Cottage",
    errorMessage: "This field is required!",
    label:"Cottage Name",
    required: true,
  },
  {
    id:2,
    name:"country",
    type:"text",
    placeholder:"Serbia",
    errorMessage:"Invalid input!",
    label:"Country",
    required: true,
    pattern: `^.{1,}$`,
  },
  {
    id:3,
    name:"city",
    type:"text",
    placeholder:"Belgrade",
    errorMessage:"Invalid input!",
    label:"City",
    required: true,
    pattern: `^.{1,}$`
  },
  {
    id:4,
    name:"street",
    type:"text",
    placeholder:"Kraljevica Marka 12",
    errorMessage:"Invalid input!",
    label:"Street",
    required: true,
    pattern: `^.{1,}$`
  },
  {
    id:5,
    name:"numOfRooms",
    type:"number",
    placeholder:"3",
    errorMessage: "Invalid input!",
    label:"Number of Rooms",
    required: true,
  },
  {
    id:6,
    name:"capacity",
    type:"number",
    placeholder:"10",
    errorMessage: "Invalid input!",
    label:"Max People",
    required: true,
  },
  {
    id: 7,
    name:"price",
    type:"number",
    placeholder:"100",
    errorMessage:"Invalid input!",
    label:"Price per Night [$]",
    required: true,
  },
  {
    id: 8,
    name:"fee",
    type:"number",
    placeholder:"50",
    errorMessage:"Invalid input!",
    label:"Cancellation Fee [$]",
    required: true,
  },
  {
    id:9,
    name:"regulations",
    type:"text",
    placeholder:"No regulations...",
    errorMessage: "This field is required!",
    label:"Regulations",
    required: true,
    multiline: true,
    rows: 5,
  },
  {
    id:10,
    name:"description",
    type:"text",
    placeholder:"Description of cottage...",
    errorMessage: "This field is required!",
    label:"Description",
    required: true,
    multiline:true,
    rows: 5,
  }
];